services:
  ws:
    image: realstraw/sbt:jdk11
    working_dir: /acdc/ws
    volumes:
      - ./:/acdc/ws
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DATA_TTL: "${DATA_TTL}"
    ports:
      - 9001:9000
    tty: true # for easy debugging
    # command:
    #   sbt ws/run
  db:
    image: postgres:16
    volumes:
      - acdc-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  flyway:
    image: flyway/flyway:latest-alpine
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      FLYWAY_URL: "jdbc:postgresql://db:5432/postgres"
      FLYWAY_USER: "postgres"
      FLYWAY_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy
    command:
      migrate

volumes:
  acdc-postgres-data:
